{
    "timestamp": "2025-05-06T12:03:11.556634",
    "scan_results": {
        "port_scan": {
            "ports": {
                "80": {
                    "state": "open",
                    "reason": "syn-ack",
                    "name": "http",
                    "product": "nginx",
                    "version": "1.24.0",
                    "extrainfo": "Ubuntu",
                    "conf": "10",
                    "cpe": "cpe:/o:linux:linux_kernel",
                    "script": {
                        "http-title": "502 Bad Gateway",
                        "http-server-header": "nginx/1.24.0 (Ubuntu)"
                    }
                },
                "8080": {
                    "state": "open",
                    "reason": "syn-ack",
                    "name": "tcpwrapped",
                    "product": "",
                    "version": "",
                    "extrainfo": "",
                    "conf": "8",
                    "cpe": "",
                    "script": {
                        "http-server-header": "Apache/2.4.58 (Ubuntu)",
                        "http-title": "Site doesn't have a title (text/html).",
                        "http-open-proxy": "Proxy might be redirecting requests"
                    }
                }
            },
            "os": [
                {
                    "name": "Linux 2.6.32",
                    "accuracy": "100",
                    "line": "55742",
                    "osclass": [
                        {
                            "type": "general purpose",
                            "vendor": "Linux",
                            "osfamily": "Linux",
                            "osgen": "2.6.X",
                            "accuracy": "100",
                            "cpe": [
                                "cpe:/o:linux:linux_kernel:2.6.32"
                            ]
                        }
                    ]
                }
            ],
            "hostname": ""
        },
        "ssl_check": {
            "error": "[Errno 111] Connection refused"
        },
        "security_headers": {
            "error": "HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feffecd91c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
        },
        "packet_analysis": {
            "total_packets": 17,
            "protocols": {
                "UDP": 17
            },
            "suspicious_patterns": []
        }
    },
    "vulnerabilities": [],
    "recommendations": []
}